package com.softengunina.consigliaviaggibackoffice;
import com.softengunina.consigliaviaggibackoffice.controllers.AdminHomeController;
import com.softengunina.consigliaviaggibackoffice.models.Amministratore;

/**
 *
 * @author Alessandro Fontanella
 * @author Walter Galiano
 * @author Stefano Sivo
 */
public class AdminHome extends javax.swing.JFrame {

    private Amministratore admin;

    /**
     * Creates new form AdminHome
     * @param currAdmin
     */
    public AdminHome(Amministratore currAdmin) {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        
        admin= currAdmin;
        
        OperatoreField.setText(String.valueOf(admin.getID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminHomePanel = new javax.swing.JPanel();
        ProjectLabel = new javax.swing.JLabel();
        CompanyLabel = new javax.swing.JLabel();
        AdminHomeLabel = new javax.swing.JLabel();
        GestisciRecensioniButton = new javax.swing.JButton();
        GestisciUtentiButton = new javax.swing.JButton();
        ValidaRecensioniButton = new javax.swing.JButton();
        OperatoreLabel = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        OperatoreField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminHomePanel.setBackground(new java.awt.Color(255, 255, 255));

        ProjectLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ProjectLabel.setForeground(new java.awt.Color(51, 51, 255));
        ProjectLabel.setText("Consiglia Viaggi 19");

        CompanyLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CompanyLabel.setForeground(new java.awt.Color(51, 51, 255));
        CompanyLabel.setText("SoftEngUniNA");

        AdminHomeLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AdminHomeLabel.setForeground(new java.awt.Color(51, 51, 255));
        AdminHomeLabel.setText("ADMIN HOME");

        GestisciRecensioniButton.setBackground(new java.awt.Color(51, 51, 255));
        GestisciRecensioniButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GestisciRecensioniButton.setForeground(new java.awt.Color(255, 255, 255));
        GestisciRecensioniButton.setText("GESTISCI RECENSIONI");
        GestisciRecensioniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestisciRecensioniButtonActionPerformed(evt);
            }
        });

        GestisciUtentiButton.setBackground(new java.awt.Color(51, 51, 255));
        GestisciUtentiButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GestisciUtentiButton.setForeground(new java.awt.Color(255, 255, 255));
        GestisciUtentiButton.setText("GESTISCI UTENTI");
        GestisciUtentiButton.setPreferredSize(new java.awt.Dimension(213, 31));
        GestisciUtentiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestisciUtentiButtonActionPerformed(evt);
            }
        });

        ValidaRecensioniButton.setBackground(new java.awt.Color(51, 51, 255));
        ValidaRecensioniButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ValidaRecensioniButton.setForeground(new java.awt.Color(255, 255, 255));
        ValidaRecensioniButton.setText("VALIDA RECENSIONI");
        ValidaRecensioniButton.setPreferredSize(new java.awt.Dimension(213, 31));
        ValidaRecensioniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidaRecensioniButtonActionPerformed(evt);
            }
        });

        OperatoreLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        OperatoreLabel.setForeground(new java.awt.Color(51, 51, 255));
        OperatoreLabel.setText("Operatore:");

        LogoutButton.setBackground(new java.awt.Color(255, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("LOGOUT");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        OperatoreField.setEditable(false);
        OperatoreField.setBackground(new java.awt.Color(255, 255, 255));
        OperatoreField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        OperatoreField.setForeground(new java.awt.Color(51, 51, 255));
        OperatoreField.setBorder(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\walte\\Desktop\\ConsigliaViaggiBackOffice\\src\\main\\java\\Immagini\\ConsigliaViaggiICO.png")); // NOI18N

        javax.swing.GroupLayout AdminHomePanelLayout = new javax.swing.GroupLayout(AdminHomePanel);
        AdminHomePanel.setLayout(AdminHomePanelLayout);
        AdminHomePanelLayout.setHorizontalGroup(
            AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomePanelLayout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addComponent(AdminHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(LogoutButton)
                .addGap(20, 20, 20))
            .addGroup(AdminHomePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectLabel)
                    .addComponent(CompanyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OperatoreLabel)
                .addGap(4, 4, 4)
                .addComponent(OperatoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(AdminHomePanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ValidaRecensioniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestisciUtentiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestisciRecensioniButton))
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminHomePanelLayout.setVerticalGroup(
            AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminHomePanelLayout.createSequentialGroup()
                        .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProjectLabel)
                            .addComponent(OperatoreLabel)
                            .addComponent(OperatoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AdminHomeLabel))
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(AdminHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminHomePanelLayout.createSequentialGroup()
                        .addComponent(GestisciRecensioniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(GestisciUtentiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ValidaRecensioniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(CompanyLabel)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.dispose();
        
        AdminHomeController.clickLogout();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ValidaRecensioniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidaRecensioniButtonActionPerformed
        this.dispose();
        
        AdminHomeController.clickValidaRecensioni(admin);
    }//GEN-LAST:event_ValidaRecensioniButtonActionPerformed

    private void GestisciRecensioniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestisciRecensioniButtonActionPerformed
        this.dispose();
        
        AdminHomeController.clickGestisciRecensioni(admin);
    }//GEN-LAST:event_GestisciRecensioniButtonActionPerformed

    private void GestisciUtentiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestisciUtentiButtonActionPerformed
        this.dispose();
        
        AdminHomeController.clickGestisciUtenti(admin);
    }//GEN-LAST:event_GestisciUtentiButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminHomeLabel;
    private javax.swing.JPanel AdminHomePanel;
    private javax.swing.JLabel CompanyLabel;
    private javax.swing.JButton GestisciRecensioniButton;
    private javax.swing.JButton GestisciUtentiButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField OperatoreField;
    private javax.swing.JLabel OperatoreLabel;
    private javax.swing.JLabel ProjectLabel;
    private javax.swing.JButton ValidaRecensioniButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
