/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softengunina.consigliaviaggibackoffice;

import com.softengunina.consigliaviaggibackoffice.controllers.LoginAdminController;;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author Walter Galiano
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginAdminPanel = new javax.swing.JPanel();
        ProjectLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        AccediButton = new javax.swing.JButton();
        CompanyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        ProjectLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ProjectLabel.setForeground(new java.awt.Color(51, 51, 255));
        ProjectLabel.setText("Consiglia Viaggi 19");

        LoginLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(51, 51, 255));
        LoginLabel.setText("LOGIN AMMINISTRATORE");

        IDLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(51, 51, 255));
        IDLabel.setText("ID");

        PasswordLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 51, 255));
        PasswordLabel.setText("Password");

        AccediButton.setBackground(new java.awt.Color(51, 51, 255));
        AccediButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AccediButton.setForeground(new java.awt.Color(255, 255, 255));
        AccediButton.setText("ACCEDI");
        AccediButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccediButtonActionPerformed(evt);
            }
        });

        CompanyLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CompanyLabel.setForeground(new java.awt.Color(51, 51, 255));
        CompanyLabel.setText("SoftEngUniNA");

        javax.swing.GroupLayout LoginAdminPanelLayout = new javax.swing.GroupLayout(LoginAdminPanel);
        LoginAdminPanel.setLayout(LoginAdminPanelLayout);
        LoginAdminPanelLayout.setHorizontalGroup(
            LoginAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAdminPanelLayout.createSequentialGroup()
                .addGroup(LoginAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginAdminPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ProjectLabel))
                    .addGroup(LoginAdminPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(LoginAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDLabel)
                            .addComponent(LoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordLabel)
                            .addComponent(IDField)
                            .addComponent(PasswordField)
                            .addComponent(AccediButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(LoginAdminPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CompanyLabel)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        LoginAdminPanelLayout.setVerticalGroup(
            LoginAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAdminPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ProjectLabel)
                .addGap(18, 18, 18)
                .addComponent(LoginLabel)
                .addGap(18, 18, 18)
                .addComponent(IDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(AccediButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(CompanyLabel)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccediButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccediButtonActionPerformed
        // TODO add your handling code here:

        if(!IDField.getText().equals("")) {
            if (!PasswordField.getText().equals("")) {
                if(LoginAdminController.clickLogin(Integer.parseInt(IDField.getText()), PasswordField.getText()) == true){
                    this.dispose();
                }else{
                    IDField.setText("");
                    PasswordField.setText("");
                }
            }
        }else{
            UIManager.put("OptionPane.messageFont", new Font("Century Gothic", Font.BOLD, 18));
            UIManager.put("OptionPane.buttonFont", new Font("Century Gothic", Font.ITALIC, 16));
            JOptionPane.showMessageDialog(null,"Compilare tutti i campi!","ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_AccediButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccediButton;
    private javax.swing.JLabel CompanyLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JPanel LoginAdminPanel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel ProjectLabel;
    // End of variables declaration//GEN-END:variables
}
